src/pur_beurre/authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('profile/<str:username>/', views.UserProfile.as_view(),
         name='profile'),
]

src/pur_beurre/legal_mentions/urls.py
from django.urls import path
from .views import LegalMentionsView

app_name = 'legal_mentions'

urlpatterns = [
    path('', LegalMentionsView.as_view(), name='legal_mentions'),
]

src/pur_beurre/product_lookup/urls.py
from django.urls import path
from .views import (ProductLookupView, ProductLookupResultsView, FavoritesView,
                    ProductDetails, favorite_click)

app_name = 'product_lookup'

urlpatterns = [
    path('', ProductLookupView.as_view(), name='product_lookup'),
    path('search/<str:product_name>', ProductLookupResultsView.as_view(),
         name='product_lookup_results'),
    path('my-favorites/', FavoritesView.as_view(), name='my_favorites'),
    path('details/<int:pk>/', ProductDetails.as_view(),
         name='product_details'),
    path('ajax/toggle-favorite/<int:product_id>', favorite_click,
         name='favorite_click'),
]

src/pur_beurre/pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product_lookup.urls')),
    path('accounts/', include('authentification.urls')),
    path('mentions-legales/', include('legal_mentions.urls')),
]

if settings.ROLE != "production":
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pur_beurre/legal_mentions/models.py
from django.db import models

# Create your models here.

src/pur_beurre/product_lookup/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """Indexes categories for Products"""
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Products(models.Model):
    """Represents a product from OpenFoodFacts"""

    product_name = models.CharField(max_length=200)
    product_url = models.URLField(max_length=200)
    product_image = models.URLField(max_length=200)
    product_nutriscore = models.CharField(max_length=1)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    nutritional_information = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = "Produit"
        verbose_name_plural = "Produits"


class Favorites(models.Model):
    """Represents a favorite product"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('product_lookup.Products',
                                on_delete=models.CASCADE)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = "Favori"
        verbose_name_plural = "Favoris"
        unique_together = ('user', 'product')

src/pur_beurre/authentification/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name']

src/pur_beurre/authentification/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView

from .forms import UserRegisterForm


class MyLoginView(LoginView):
    template_name = 'authentification/login.html'
    redirect_field_name = "next"

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["next"] = reverse_lazy("product_lookup:product_lookup")
        return context


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'authentification/create_account.html'
    success_url = reverse_lazy('authentification:login')
    form_class = UserRegisterForm
    success_message = "Votre compte a été créé avec succès !"


class MyLogoutView(LogoutView):
    """This view de-auth the user, and redirects to login"""
    next_page = reverse_lazy('authentification:login')


class UserProfile(LoginRequiredMixin, DetailView):
    """This view displays the user profile"""
    model = User
    template_name = 'authentification/user_profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

src/pur_beurre/legal_mentions/views.py
from django.views.generic import TemplateView


class LegalMentionsView(TemplateView):
    """
    Class-based view for legal_mentions.html.
    """
    template_name = 'legal_mentions/legal_mentions.html'

src/pur_beurre/product_lookup/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView

from .models import Products, Favorites


class ProductLookupView(TemplateView):

    template_name = 'product_lookup/product_lookup.html'

    def post(self, request, *args, **kwargs):
        """
        This method is called when the user submits the form.
        """
        product_name = request.POST['product_name']
        return HttpResponseRedirect(reverse(
            'product_lookup:product_lookup_results',
            args=[product_name])
            )


class ProductLookupResultsView(TemplateView):

    template_name = 'product_lookup/product_lookup_results.html'

    def get_context_data(self, **kwargs) -> dict:

        context = super().get_context_data(**kwargs)
        product_name = kwargs['product_name']

        # Get the first item that matches the query to look for
        # alternatives in databases
        searched_product = Products.objects.filter(
            product_name__icontains=product_name).first()
        context['searched_product'] = searched_product

        # Get the alternatives to the found product

        if searched_product:
            alternatives = Products.objects.filter(
                product_nutriscore__lte=searched_product.product_nutriscore,
                product_category=searched_product.product_category
                ).exclude(
                product_name=searched_product.product_name
                ).order_by('product_nutriscore')
            context['alternatives'] = alternatives
        else:
            context['alternatives'] = None

        # Get the list of products ids that the user has already
        # added to his favorites
        if self.request.user.is_authenticated:
            user_favorites = self.request.user.favorites_set.all()
            fav_id_list = [favorite.product.id for favorite in user_favorites]
            context['favorites_id_list'] = fav_id_list
        else:
            context['favorites_id_list'] = None

        return context


def favorite_click(request, *args, **kwargs):
    """
    This method is called when the user clicks on the favorite button.
    """
    product_id = request.POST.dict()['product_id']
    product = Products.objects.get(pk=product_id)
    user = request.user

    is_favorite = Favorites.objects.filter(
        user=user, product=product).exists()
    if is_favorite:
        # Remove the favorite
        Favorites.objects.filter(
            user=user, product=product).delete()
    else:
        # Add the favorite
        Favorites.objects.create(user=user, product=product)

    return HttpResponse(status=200)


class FavoritesView(LoginRequiredMixin, TemplateView):

    template_name = 'product_lookup/favorites.html'

    def get_context_data(self, **kwargs) -> dict:

        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Get the list of products ids that the user has already
        # added to his favorites
        user_favorites = Favorites.objects.filter(user=user)
        context['favorites'] = user_favorites

        context['favorites_id_list'] = \
            [product.product.id for product in user_favorites]

        return context


class ProductDetails(DetailView):
    model = Products
    template_name = 'product_lookup/product_details.html'

src/pur_beurre/authentification/templates/authentification/create_account.html
{% extends 'product_lookup/base.html' %}
{% load crispy_forms_tags %}

{% block appcontent %}

{% if form.errors %}
<p>Le mot de passe ou l'email semble incorrect. Veuillez réessayer.</p>
{% endif %}

<form method="post" action="{% url 'authentification:signup' %}" class="d-flex flex-column col-10 col-lg-5 mx-auto mt-3">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Confirmer" class="btn btn-primary mx-auto mt-3">
    </form>


{% endblock appcontent %}

src/pur_beurre/authentification/templates/authentification/login.html
{% extends 'product_lookup/base.html' %}
{% load crispy_forms_tags %}

{% block appcontent %}


<form method="post" action="{% url 'authentification:login' %}" class="d-flex flex-column col-10 col-lg-5 mx-auto mt-3">
    {% if form.errors %}
    <p>Le mot de passe ou l'email semble incorrect. Veuillez réessayer.</p>
    {% endif %}
    {% if messages %}
    <ul class="alert alert-success" role="alert">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% csrf_token %}
{{ form|crispy }}

<input type="submit" value="Se connecter" class="btn btn-primary mx-auto mt-3">
<input type="hidden" name="next" value="{{ next }}">
<small class="mt-3">
    <a href="{% url 'authentification:signup' %}">Pas encore de compte ? Cliquez ici pour en créer un !</a>
</small>
</form>



{% endblock appcontent %}

src/pur_beurre/authentification/templates/authentification/user_profile.html
{% extends 'product_lookup/base.html' %}
{% load static %}
{% block appcontent %}

    <header id="profile_banner" class="d-flex flex-column col-12 mb-4">
        <div id="profile_banner_text" class="d-flex flex-column col-12 col-lg-4 m-auto">
            <h1 class="mx-auto">Ahoy</h1>
            <h2 class="mx-auto">{{ user.username }}&nbsp;!</h2>
        </div>
    </header>

    {% if request.user.username == object.username %}
        <div class="d-flex col-10 col-lg-6 mx-auto mt-3">
            <p class="mx-auto">Votre adresse email est : {{ object.email }}</p>
        </div>
    {% else %}
        <div class="d-flex col-10 col-lg-6">
            <p>Vous n'avez pas la permission de voir ceci.</p>
        </div>
    {% endif %}

{% endblock appcontent %}

src/pur_beurre/legal_mentions/templates/legal_mentions/legal_mentions.html
{% extends 'product_lookup/base.html' %}

{% block appcontent %}

<section class="page-section" id="mentions-légales">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Notice légale</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">
                    Site construit pour le projet 8 du parcours développeur d'application python d'OpenClassrooms<br>
                </p>
                <p class="text-muted mb-5">
                    <h3>Hébergeur</h3>
                    Linode
                    
                    249 Arch St Philadelphia, PA, 19106-1915 United States 
                </p>
                <p class="text-muted mb-5">
                    <h3>Crédits</h3>
                    <ul>
                        <li>Icône <a href="https://thenounproject.com/term/carrot/29691/">"Carrot"</a> par <a href="https://thenounproject.com/FabienJ/">Fabien Jouin</a> sur
                            <a href="https://thenounproject.com">the Noun Project</a>
                        </li>
                        <li>
                            <a href="https://unsplash.com/photos/eqsEZNCm4-c">Photo de fond de la page d'accueil</a> par <a style="background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@olenka_kotyk?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Olenka Kotyk"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Olenka Kotyk</span></a> sur Unsplash
                        </li>
                    </ul>
                <p class="text-muted mb-5">
                    <h3>Dispositions légales</h3>
                    {% lorem 2 p %}
                </p>
                <p class="text-muted mb-5">
                    <h3>Respect du droit d’auteur</h3>
                    {% lorem 2 p %}
                </p>
                <p class="text-muted mb-5">
                    <h3>Droit des bases de données</h3>
                    {% lorem 2 p %}
                </p>
                <p class="text-muted mb-5">
                    <h3>Établissement de liens</h3>
                    {% lorem 2 p %}
                </p>
                <p class="text-muted mb-5">
                <h3>Contact concepteur</h3>
                <ul>
                    <li class="nav-item"><a href="https://www.linkedin.com/in/benjamin-mourgues-33000/">LinkedIn</a></li>
                    <li class="nav-item"><a href="https://github.com/Shriukan33/P8_Plateforme_pur_beurre">Github</a></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock appcontent %}

src/pur_beurre/product_lookup/templates/product_lookup/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
{% block html %}
<head>
{% block head %}

    <title>{% block title %}Pur Beurre{% endblock %}</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap 5.1.3 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'product_lookup/logo_pur_beurre-favicon.png' %}" />
    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'product_lookup/pur_beurre.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

{% endblock head %}
</head>

<body>
{% block body %}

    {% block navbar %}
    <nav id="navbar" class="d-flex navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a id="navbar_logo" class="navbar-brand" href="{% url 'product_lookup:product_lookup' %}">
                <img src="{% static 'product_lookup/logo_pur_beurre.png' %}" alt="logo_pur_beurre" width="30" height="30">
                <span>Pur Beurre</span>
            </a>

            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <!-- NavLink Menu -->
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="d-flex nav-item">
                        <form method="POST" action="{% url 'product_lookup:product_lookup'%}"
                        class="d-flex flex-row">
                            {% csrf_token %}
                            <div class="input-group my-auto mx-3 ">
                                <input type="text" class="form-control align-middle" placeholder="Chercher un aliment..."
                                aria-label="Chercher un aliment..." aria-describedby="basic-addon2" name="product_name" required>
                                <div class="input-group-append">
                                    <button class="btn search-btn" type="submit">
                                        <i class="fas fa-search" alt="Lancer la recherche" title="Lancer la recherche"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </li>
                    <li class="d-flex nav-item">
                        {% if request.user.is_authenticated %}
                            {% with request.user.username as username %}
                            <a class="nav-link mx-lg-3 mx-auto d-flex flex-row" href="{% url "authentification:profile" username %}" style="color: gray"><i class="fas fa-user-circle fa-2x" alt="Mon compte" title="Mon compte"></i>
                                <span class="aligned-icon ">Mon compte</span>
                            </a>
                            {% endwith %}
                        {% else %}
                        <a class="nav-link mx-lg-3 mx-auto d-flex flex-row" href="{% url "authentification:login" %}" style="color: gray"><i class="fas fa-user-circle fa-2x" alt="Mon compte" title="Mon compte"></i>
                            <span class="aligned-icon ">Mon compte</span>
                        </a>
                        {% endif %}

                    </li>
                    <li class="d-flex nav-item">
                        <a class="nav-link mx-lg-3 mx-auto d-flex flex-row" href="{% url 'product_lookup:my_favorites' %}">
                            <img src="{% static 'product_lookup/carot.png' %}" height="30" width="30" alt="Mes aliments" title="Mes aliments"/>
                            <span class="aligned-icon ">Mes aliments</span>
                        </a>
                    </li>
                    <li class="d-flex nav-item">
                            {% if request.user.is_authenticated %}
                            <a class="nav-link mx-lg-3 mx-auto d-flex flex-row" href="{% url "authentification:logout" %}">
                                <i class="fas fa-sign-out-alt fa-2x" alt="Se déconnecter" title="Se déconnecter"></i>
                                <span class="aligned-icon ">Se déconnecter</span>
                            </a>
                            {% else %}
                            <a class="nav-link mx-lg-3 mx-auto d-flex flex-row" href="{% url "authentification:login" %}">
                                <i class="fas fa-sign-in-alt fa-2x" alt="Se connecter" title="Se connecter"></i>
                                <span class="aligned-icon">Se connecter</span>
                            </a>
                            {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% endblock navbar %}

    {% block appcontent %}
        <h1> Hello world </h1>
    {% endblock appcontent %}

    <div class="my-5"></div>
    <footer class="fixed-bottom mt-5 py-3 bg-light">
    {% block footer %}
        <div class="container">
            <div class="row">
                <nav id="footer-nav" class="d-flex col-sm-12 justify-content-around">
                    <a href="{% url 'legal_mentions:legal_mentions' %}" class="d-flex flex-grow-1 justify-content-center">Mentions légales</a>
                    <a href="{% url "product_lookup:product_lookup" %}#contact" class="d-flex flex-grow-1 justify-content-center">Contact</a>
                </nav>
            </div>
        </div>
    {% endblock footer %}
    </footer>

    {% block javascript %}
        <!--jQuery & Popper for Bootstrap 5.1.3 -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- Font Awesome -->
        <script src="https://kit.fontawesome.com/31825b4d8e.js" crossorigin="anonymous"></script>

        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    {% endblock javascript %}

{% endblock body %}
</body>

{% endblock html %}
</html>

src/pur_beurre/product_lookup/templates/product_lookup/favorites.html
{% extends 'product_lookup/product_lookup_results.html' %}
{% load static %}

{% block appcontent %}

<section id="results" class="d-flex col-10 col-md-8 flex-wrap justify-content-around mx-auto">
    {% for product in favorites %}
        <div class="d-flex col-10 col-md-4 flex-column mt-3 p-4 position-relative">
            <div>
                <a href="{% url 'product_lookup:product_lookup_results' product.product.product_name %}" >
                <img src="{{product.product.product_image}}" alt="{{product.product.product_name}}" class="result-img d-flex m-auto img-fluid">
                <div class="nutriscore-badge nutriscore-{{product.product.product_nutriscore}}">{{product.product.product_nutriscore}}</div>
                </a>
            </div>
            <h2 class="my-3 py-2 text-center">
                <a href="{% url 'product_lookup:product_details' product.product.id %}"
                style="text-decoration:none;color:inherit;"> 
                    {{product.product.product_name}}
                </a>
            </h2>
            <button id="product_add_{{ product.product.id }}" class="d-flex save-btn" name="save_button">
                <span class="mx-auto">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'authentification:login'%}">
                    {% else %}
                        {% comment %} <a href="{% url 'product_lookup:save_product' product.id %}"> {% endcomment %}
                        <a href='#'>
                    {% endif %}
                    <i class="fa fa-floppy-o" aria-hidden="true">&nbsp;Sauvegarder</i>
                    </a>
                </span>
            </button>
            <button id="product_remove_{{ product.product.id }}" class="save-btn remove" name="remove_button" style="display: none">
                <span class="mx-auto">
                    {% comment %} <a href="{% url 'product_lookup:remove_product' product.id %}"> {% endcomment %}
                    <a href='#'>
                        <i class="fa fa-trash-o" aria-hidden="true">&nbsp;Supprimer</i>
                    </a>
                </span>
            </button>
        </div>
    {% empty %}
        <p>Aucun Favoris pour le moment !</p>
    {% endfor %}

{% endblock appcontent %}

src/pur_beurre/product_lookup/templates/product_lookup/product_details.html
{% extends 'product_lookup/base.html' %}
{% load static %}

{% block appcontent %}
<header style="background-color: black;">
    <div class="container position-relative">
        <div id="search-results-header" class="d-flex flex-column"
        style="background-image: url({{object.product_image}})">
        </div>
        <h1 id="search-results-header-text" class="d-flex m-auto position-absolute justify-content-center">
            {{ object.product_name }}
        </h1>
    </div>
</header>

<div class="d-flex flex-column mt-4">
    <div class="d-flex flex-wrap mx-auto justify-content-around col-10">
        <img src="{% get_static_prefix %}product_lookup/nutri-{{ object.product_nutriscore }}.png"
        alt="Nutriscore {{object.product_nutriscore}}" style="height:80px;width:150px;"
        class="d-flex flex-column mx-auto col-10 col-md-6">
        <img src="{{ object.nutritional_information }}" alt="nutritional_information" class="d-flex m-auto col-10 col-md-4"
        style="max-height:30vh;max-width:auto;">
    </div>
    <a href="{{ object.product_url }}" class="d-flex mx-auto justify-content-center col-10 col-md-6 mt-4">
        <button class="btn btn-primary">
            Voir la fiche d'OpenFoodFacts
        </button>
    </a>
</div>
{% endblock appcontent %}

src/pur_beurre/product_lookup/templates/product_lookup/product_lookup.html
{% extends 'product_lookup/base.html' %}
{% load static %}

{% block appcontent %}
    <header>
        <div id="homepage_header" class="d-flex flex-column">
            <div id="homepage_header_text" class="d-flex flex-column mx-auto mb-3 mt-auto col-8">
                <h1>Du gras, oui, mais de la qualité!</h1>
                <h2>
                    Trouvez un produit de substitution pour ceux
                    que vous consommez tous les jours
                </h2>
            </div>
            <div id="homepage_header_searchbar" class="d-flex mx-auto mb-auto col-10 col-md-4">
                <form method="POST" action="{% url 'product_lookup:product_lookup' %}"
                class="d-flex flex-row mx-auto">
                    {% csrf_token %}
                    <input type="text" class="form-control align-middle" placeholder="Produit"
                    aria-label="Produit" aria-describedby="basic-addon2" name="product_name" required>
                    <div class="input-group-append">
                        <button class="btn search-btn" type="submit">
                            Chercher
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </header> <!-- /header -->

    <section id="presentation" class="d-flex flex-column">
        <div class="d-flex flex-column mx-auto justify-content-center">
            <h2 class="mx-auto mt-4">Colette et Remy</h2>
            <hr class="mx-auto" style="width: 10%;">
            <p class="d-flex col-10 col-lg-4 mx-auto ">
                Colette et Remy sont deux amis qui se sont rencontrés
                dans un restaurant parisien, alors tous deux cuisiniers.
                Passionnés par la cuisine et la nutrition, ils s'associent
                pour créer un site de recherche de produits de substitution
                pour aider les personnes à manger plus sainement sans sacrifier
                le goût du produit.
            </p>
        </div>
        <div class="d-flex flex-wrap col-12 col-lg-6 justify-content-around mx-auto">
            <figure class="d-flex flex-column col-6 col-lg-3">
                <img src="{% static 'product_lookup/colette.png'%}"
                alt="colette" class="mx-auto" />
                <figcaption class="mx-auto">Colette</figcaption>
            </figure>
            <figure class="d-flex flex-column col-7 col-lg-3" >
                <img src="{% static 'product_lookup/remy-cropped.png'%}"
                alt="remy"
                class="mx-auto"/>
                <figcaption class="mx-auto">Remy</figcaption>
            </figure>
        </div>
        <hr style="width:100%;">
    </section> <!-- end of presentation -->

    <section id="contact">
        <div class="d-flex flex-column col-10 col-lg-4 mx-auto">
            <h2 class="mx-auto">Contactez-nous</h2>
            <hr class="mx-auto" style="width: 10%;">
            <p class="mx-auto mb-5">
                Vous avez des questions ? N'hésitez pas à nous contacter.
            </p>
        </div>

        <div id="contact_info" class="d-flex col-10 col-lg-4 mx-auto mb-5 justify-content-around">
            <div id="contact_info_phone" class="d-flex flex-column">
                <i class="fas fa-phone-alt fa-5x mx-auto mb-3"></i>
                <p>01 23 45 67 89</p>
            </div>
            <div id="contact_info_mail" class="d-flex flex-column">
                <i class="fas fa-envelope fa-5x mx-auto mb-3"></i>
                <p>mail@mail.com</p>
            </div>
        </div>

    </section> <!-- end of contact -->

{% endblock appcontent %}